### ISSUE TITLE
Add argparse for spotitude.py

### ISSUE THREAD

**Issue by dtcrout** [dtcrout/spotitude#1]
Add argparse to `spotitude.py`. For now, just add a parameter for `time_range`. The available values for `time_range` are:

* `short_term` (set as default term)
* `medium_term`
* `long_term`

Acceptance criteria:
* Add argparse to `spotitude.py`
* Update `README.md` with instructions on how to specify the time range

**Comment by polarCatZhao** [comment]
Hi @dtcrout ,
I would like to help with this issue. Do you mean something like instead of the top 25 tracks, the users can now specify  top n tracks they are interested?

**Comment by dtcrout** [comment]
Hi @polarCatZhao ,

Feel free to contribute to the project. I updated the issue details with the requirements and an acceptance criteria. I also updated the readme on submitting a pull request. If you have any questions, let me know!

**Comment by polarCatZhao** [comment]
Hi @dtcrout ,

Yeah I saw your update! Thank you for your swift response and thank you for welcoming me to the project! I'm a first time contributor and I really appreciate it.

I tried to follow the README.md and made spotitude.py run locally. Everything worked fine but I had trouble with the credentials. I created an app on Spotify and got the Client ID and Client Secret. I used the username of my Spotify account as the USERNAME and put "user-top-read" as the SCOPE, but what should be the REDIRECT_URI?

**Comment by dtcrout** [comment]
Hi @polarCatZhao ,

The `REDIRECT_URI` can be whatever you would like, e.g `http://www.google.com/`. You will also need to configure the `REDIRECT_URI` in your app through the Spotify developers dashboard. Just make sure that the redirect URI in the app and on your account are exactly the same.

I hope that helps!

**Comment by polarCatZhao** [comment]
@dtcrout It worked!!!! The visualization is so cool! I will start to work on adding argparse.
