### ISSUE TITLE
Unicode doesn't display properly in visualization

### ISSUE THREAD

**Issue by zackelia** [dtcrout/spotitude#15]
The HTML boilerplate code is missing `<meta charset="utf-8">` in the head code so unicode characters get displayed as other symbols. (ex. Sigrid - _Don’t Feel Like Crying_ - has a special quotation mark)

**Comment by dtcrout** [comment]
@zackelia, thanks for pointing this out! If you want to submit a PR, I would be happy to accept it.

**Comment by dtcrout** [comment]
@zackelia Thanks for fixing this!
