### ISSUE TITLE
Create playlist and add to visualization

### ISSUE THREAD

**Issue by dtcrout** [dtcrout/spotitude#2]
Compile a playlist based on top tracks and provide the link on the bottom of the visualization.

**Comment by polarCatZhao** [comment]
@dtcrout I would like to work on this!

**Comment by dtcrout** [comment]
@polarCatZhao , when I get some time I'll break down this feature into subtasks!

**Comment by polarCatZhao** [comment]
@dtcrout , thanks! That would be great.

**Comment by dtcrout** [comment]
I created two subtasks for playlist generation (#9) and delivery (#10).
