### ISSUE TITLE
Add documentation on how to setup spotitude.config

### ISSUE THREAD

**Issue by dtcrout** [dtcrout/spotitude#3]
Setting up the `spotitude.config` seems to be non-trivial for newcomers. There should be a step-by-step guide on how to get the config file working.

Acceptance Criteria:
* Provide a step-by-step guide on setting up the `spotitude.config` file
  * This guide should include screenshots on where to find the required values as well as the proper links
* Name the file `SETUP.md`
* Link to `SETUP.md` in `README.md` under the configuration section
* Section with common issues and fixes
  * This can be obtained by the issues listed here in this thread

**Comment by mohitrajane** [comment]
Hey i work like to take up this issue. I can't setup the config my self i am getting an illegal scope error. It apparently is a issue with [spotify web  api](https://github.com/spotify/web-api/issues/1262l).


I tried to set scope as nothing in config file and i got the response url but got a forbidden 403 error in the terminal.

Hope you can help me get started :)

**Comment by dtcrout** [comment]
Hi @mohitrajane , glad to have you working on the issue.

When setting up the Spotify API:

* Your username is what is found when you go to `Profile` > `Account` > `Account Overview`
* Scope is _required_ in order to get the API working. I updated the `Makefile` so it gives the proper scope
* The redirect URI needs to be configured in your Spotify app in your developers account. Make sure that the redirect URI is _exactly_ the same between your app and what's in `spotitude.config`, e.g. one cannot be `https://google.com/` and the other `https://google.com`

Also, while these values are strings, in the config file they cannot be in quotes, i.e. `'` or `"`.

I hope this helps, and if you have further questions let me know.

**Comment by polarCatZhao** [comment]
That would be so nice to have a config setup guide! @mohitrajane I always log in with my Facebook account, so I don't have a username in the Profile > Account > Account Overview. My username is a string of automatically generated code which can only be found in the Spotify mobile app Settings > Account. Maybe that's a special case for people logging in with Facebook accounts?

**Comment by mohitrajane** [comment]
@dtcrout What I meant is the scope `user-read-first` is not working it is giving me a illegal scope error and when i searched online it seemed like a problem with the spotify api. 

It is popping up on spotify's issues [link](https://github.com/spotify/web-api/issues/1262)

**Comment by polarCatZhao** [comment]
Hi @mohitrajane ! The scope is `user-top-read` and not `user-read-first` as in your comment. Maybe that's the cause for the illegal scope error you are getting?

**Comment by mohitrajane** [comment]
@polarCatZhao  I tired it with `user-top-read` also. Output: 
![2019-06-05-120601_1920x1080_scrot](https://user-images.githubusercontent.com/25960817/58935202-6f0efa80-878a-11e9-83b5-f27615c06903.png)

My config file
![2019-06-05-120808_1920x1080_scrot](https://user-images.githubusercontent.com/25960817/58935292-b9907700-878a-11e9-974e-b59dfb9c88b9.png)

**Comment by dtcrout** [comment]
Since you're using `localhost` as your redirect uri, do you have the page being served? If not, then that might be the issue. Fortunately Python makes it easy to do this. Get a page up and running using this command:

`$ touch index.html && python3 -m http.server`

I think Python uses port `8000` as default, so change your redirect uri to `http://localhost:8000` in both the config file and Spotify app.

Alternatively, just use `https://google.com` for your redirect uri.

**Comment by mohitrajane** [comment]
I think it is a scope specific issue. when i try it with no scope
I am getting the authorization page.
Config : 
![2019-06-05-204327_1920x1080_scrot](https://user-images.githubusercontent.com/25960817/58967901-b1f4c080-87d2-11e9-8b10-159754366226.png)

Browser response:
![2019-06-05-204120_1920x1080_scrot](https://user-images.githubusercontent.com/25960817/58967930-bcaf5580-87d2-11e9-8d8d-417b7e0b9125.png)

**Comment by mohitrajane** [comment]
@dtcrout this tool can't seem to be used with the scope `user-top-read` which is not working. Should that be changed for are you planning on waiting for spotify to fix it?

**Comment by dtcrout** [comment]
@mohitrajane , I would suggest to look into seeing if you have the proper values for your `USERNAME` and `REDIRECT_URI`.

**Comment by nicofilliol** [comment]
I used https://google.com as my redirect URI. So after the authorization page, I am being redirected there and I paste the URL into the terminal as it is asked by the spotitude script. However, next I get the following error:
```
Traceback (most recent call last):
  File "/anaconda3/envs/spotitude/lib/python3.7/site-packages/spotipy/client.py", line 119, in _internal_call
    r.raise_for_status()
  File "/anaconda3/envs/spotitude/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.spotify.com/v1/me/top/tracks?time_range=short_term&limit=25&offset=0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "spotitude.py", line 37, in <module>
    spotify, limit=25, time_range=args.time_range, save=True
  File "/Users/Nico/Desktop/Python/spotitude/data.py", line 39, in get_top_tracks
    top_tracks = spotify.current_user_top_tracks(limit=limit, time_range=time_range)
  File "/anaconda3/envs/spotitude/lib/python3.7/site-packages/spotipy/client.py", line 669, in current_user_top_tracks
    offset=offset)
  File "/anaconda3/envs/spotitude/lib/python3.7/site-packages/spotipy/client.py", line 146, in _get
    return self._internal_call('GET', url, payload, kwargs)
  File "/anaconda3/envs/spotitude/lib/python3.7/site-packages/spotipy/client.py", line 127, in _internal_call
    -1, '%s:\n %s' % (r.url, 'error'), headers=r.headers)
spotipy.client.SpotifyException: http status: 403, code:-1 - https://api.spotify.com/v1/me/top/tracks?time_range=short_term&limit=25&offset=0:
 error
```

Any idea what might be the problem? I checked all my settings in the config file and also deleted the token cache in order to try again.

**Comment by nicofilliol** [comment]
I have the exact same problem as @mohitrajane. Using `user-top-read` gives me an `Illegal scope` error and leaving the scope empty in the config file results in a 403 client error, meaning that spotitude isn't authorized in reading the user's top artists/tracks.  I also double checked all my values in the config file and I used https://google.com as my redirect URI. Is there any workaround for this since this seems to be a problem from Spotify's side [(issue 1262)](spotify/web-api#1262)?

**Comment by dtcrout** [comment]
@nicofilliol ,

I re-ran the code and didn't have an issue with the values in my config. I would suggest reading the comments in this issue to get some more insights. Some things I would suggest as they're common is to double check your redirect url in your config file and app and make sure they are _exactly_ the same. The values in your config file shouldn't contain any quotes and the username is not what you use to log into your account. It can be found in your settings logging into Spotify.

It also helps to make sure you are running the app with the proper version of Python with the dependencies installed.

The API can be tough to work with, but we'll do our best to get it working for you.

**Comment by nicofilliol** [comment]
@dtcrout Thanks a lot for your help. 

The weird thing is that the whole authorization process works with a different scope set, so I don't really see how my config settings could be the problem (but of course I triple checked them either way). However, the script is then unable to load the user top tracks because it needs a token with `user-top-read` scope for that. When you say you re-run your code, did you also delete your cached token (and maybe also delete spotitude from apps on Spotify account) so that you have to go through the whole authorization process again? If it still works for you like that we can be sure that it isn't a problem from Spotify's side.

**Comment by dtcrout** [comment]
@nicofilliol ,

I cleared my cache and re-ran my code and it works. If it works for another scope, then it could be a problem on Spotify's side. I can try creating a new app and try with those credentials.

In the meantime, do you mind opening an issue and reference it in this thread?

**Comment by nicofilliol** [comment]
@dtcrout I just got it running. It is somehow getting ridiculous though. 

I created a new app on the Spotify Developers Dashboard with the new instructions in the ReadMe with the localhost server. With some changes (`localhost:8080` threw an invalid redirect error --> changed to` 0.0.0.0:80` fixed it), the authorization worked. However, I decided to try again and took https://spotitude.me/ as redirect URI but this time again, `illegal scope` was the result. Just to be sure, I created another app on Spotify Developers with the exact same settings as before and this time it worked. I can't really explain this, but maybe this really is a bug from Spotify's side. 

At least we know a workaround for now: **just continue creating new apps on the Spotify Developers Dashboard until it works.**

**Comment by dtcrout** [comment]
@nicofilliol , glad to hear it worked out! I'll update this issue so the guide can include common issues and potential fixes.

**Comment by ldyim** [comment]
Do you mind if I work on this as well?

**Comment by dtcrout** [comment]
@ldyim , I don't think anyone is working on it right now. Go right ahead!

**Comment by nolanee** [comment]
It seems like people who were previously working on this have stopped? Is it okay if I start?

**Comment by dtcrout** [comment]
@nolanee , it's been a while so I don't see why not!
