### ISSUE TITLE
Break line not working when  config file is created 

### ISSUE THREAD

**Issue by mohitrajane** [dtcrout/spotitude#4]
This is how the template config file is created for me  after executing 

`make config`

![2019-06-03-111007_1920x1080_scrot](https://user-images.githubusercontent.com/25960817/58778561-b95c7400-85f0-11e9-904c-6bde9413ad47.png)
I am assuming it should look like this
![2019-06-03-111619_1920x1080_scrot](https://user-images.githubusercontent.com/25960817/58778723-49022280-85f1-11e9-89ad-e75b7fd838a4.png)

**Comment by dtcrout** [comment]
That's interesting. Can you update the issue with what OS you're using?

**Comment by mohitrajane** [comment]
Os: Solus 4.0 
Shell : Zsh 
Its in working in a normal shell

```
 $ echo 'hello\nhi'
 hello  
 hi   
```

and it works as intended

**Comment by dtcrout** [comment]
Perhaps there's an incompatibility with GNU's `echo` compared to the BSD one which is on Mac OS? Do you mind making a fix then submit a pull request?

**Comment by polarCatZhao** [comment]
I have the same issue. After I manually adjusted the format, the config file could be successfully parsed.

**Comment by dtcrout** [comment]
@polarCatZhao , just so I have a better understanding of this issue, can you please share your OS? Thanks!

**Comment by polarCatZhao** [comment]
@dtcrout 
OS: Windows 10
I used Git Bash to run the `make config` command.

**Comment by dtcrout** [comment]
@mohitrajane , sorry I had to revert the merge. I tested on my machine and the flag `-e` prints to the file. Investigating the issue more, `echo` isn't portable, so we need to look for a solution which works for both GNU and BSD `echo`.

**Comment by mohitrajane** [comment]
@dtcrout  ill look into it. :)
