### ISSUE TITLE
Create class for playlist generation

### ISSUE THREAD

**Issue by dtcrout** [dtcrout/spotitude#9]
As a user of Spotitude, I would like a feature such that when I get my top 25 tracks, I would like to create a playlist containing those tracks which I can then share with other people.

A new class can be created, which can contain methods to create a playlist, add tracks to that playlist, and have attributes which include the playlist id, playlist url, playlist name and playlist description. The playlist name and description should include the time range of the top tracks which makes sense to the user, i.e. `short range` top tracks should be called as `Last 4 weeks`, `medium range` should be referred as `Last 6 months` and `long range` should be referred as `All time`. Playlist descriptions should describe the time range as well, like `Top 25 tracks for last 4 weeks. Generated my spotitude.me`.

Acceptance criteria:
* Create a new file called `playlist.py`
* Create a new class called `Playlist`
* Create methods which creates playlists as well as adds tracks to playlists
* Playlist name should be called `spotitude ___` where the blank should be the time range in human readable form
* Playlist description should follow a similar format such as `Top 25 tracks for last 4 weeks. Generated my spotitude.me`

**Comment by nicofilliol** [comment]
I am new to contributing to open source projects but this seems like something appropriate as a first issue. Plus I like the idea of the project because I really miss such a feature within Spotify itself. Can I give this a try during the next few days?

**Comment by dtcrout** [comment]
@nicofilliol yes please work on this enhancement! If you have any questions let me know.

**Comment by nicofilliol** [comment]
The spotipy version installed from the `requirements.txt ` doesn't take a description argument when creating a new playlist. In order for `spotipy.client.user_playlist_create(self, user, name, public=True, description=''):` to work properly, the github version of spotipy needs to be installed.

```
pip install git+https://github.com/plamere/spotipy.git --upgrade
```

Would it be possible to include this version of spotipy in the `requirements.txt` file?

**Comment by dtcrout** [comment]
Playlist class now implemented.
